name: 'Build Docker Images using Cache'
description: 'Docker Stack CI Solution'
inputs:
  dockerfile:
    description: 'Dockerfile to build images from'
    required: true
  context:
    description: 'Docker build context'
    required: true
  args:
    description: 'Arguments for tagging as a JSON string'
    required: true
  registry:
    description: |
        Docker Registry to push images to.

        Blank for DockerHub.
        GitHub Packages example: docker.pkg.github.com/\$\{\{ github.repository \}\}/ (trailing slash is required)
    required: false
  deploy-images:
    description: JSON array of image aliases which should be deployed
    required: true
  deploy-server-docker-sudo:
    description: true to use sudo to run docker commands on deploy server
    required: true
  deploy-server-registry:
    description: local registry to push images to
    required: true
outputs:
  image-names:
    description: Image names available in the registry
  build-commands:
    description: Script to build and push images
  push-to-local-registry:
    description: Script to pull remote images and push them to local registry
  export-local-registry-names:
    description: Script to export image names from local registry
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.dockerfile }}
    - ${{ inputs.context }}
    - ${{ inputs.args }}
    - ${{ inputs.registry }}
    - ${{ inputs.deploy-images }}
    - ${{ inputs.deploy-server-docker-sudo }}
    - ${{ inputs.deploy-server-registry }}
