# From https://docs.docker.com/develop/develop-images/multistage-build/#use-multi-stage-builds

FROM golang:1.7.3 AS dependencies
# tag-as go1.7.3
WORKDIR /go/src/github.com/alexellis/href-counter/
RUN go get -d -v golang.org/x/net/html  

FROM dependencies AS compilation
# tag-as cgo - $CGO_ENABLED _ $COMMIT
COPY app.go .
ARG CGO_ENABLED
RUN CGO_ENABLED=$CGO_ENABLED GOOS=linux go build -a -installsuffix cgo -o app .

FROM alpine:latest AS href_counter_app
# tag-as final - hc - $COMMIT
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=compilation /go/src/github.com/alexellis/href-counter/app .
CMD ["./app"]
